### PR TITLE
constants: Support typedefs

### LINKED ISSUE #120: Constant values for typedefs
We need to support things like,

    typedef i32 Foo

    const Foo x = 42

Currently, the checks performed by the constant value linker will fail for these cases.

### PR DESCRIPTION
**Pull request by abhinav**
Resolves #120

CC @prashantv @kriskowal

### CODE REVIEW

File: gen/constant.go [hunk 1]
```diff
@@ -45,73 +45,97 @@ func Constant(g Generator, c *compile.Constant) error {
...
+	s := fmt.Sprint(int(v))
+	switch t {
+	case compile.I8Spec, compile.I16Spec, compile.I32Spec, compile.I64Spec:
+		// do nothing
+	default:
+		n, err := typeName(g, t)
+		if err != nil {
+			return "", err
+		}
+		s = fmt.Sprintf("%v(%v)", n, s)
```
Comment (prashantv) [inline gen/constant.go]: since the casting logic is always the same, should we have a function that does that?
then you could just do,
```go
default:
  return wrapType(g, t, s)
```

**Comment by prashantv** [comment]
lgtm with small comment

File: gen/constant.go (hunk 1 above)
Comment (abhinav) [inline gen/constant.go]: 👍

**Comment by abhinav** [comment]
Updated

**Comment by prashantv** [comment]
lgtm
