### PR TITLE
Generate req/res structs for service functions

### LINKED ISSUE #36: Provide a safe way to determine if the returned err is an application error
Given the IDL:
```
  ResolveReply Resolve(1: required ResolveRequest request) throws (
    1: InvalidServiceName invalidWatchServiceName
    2: InvalidEnsembleName invalidName
  )
```

and the call:
```
  res, err := client.Watch(ctx, request)
```

I need to differentiate between and application error and a transport error. Right now I have:

```
    switch t := err.(type) {
    case *idl.InvalidServiceName:
    case *idl.InvalidEnsembleName:
    default:
      log.Infof("tchannel error")
   }
```

But that's dangerous because if someone adds a new application exception and forgets to update the code we'll treat it as a tchannel error.

Since we probably can't change the signature of the Watch() function, we'll need something like
```
func IsWatchAppException(err) bool
```

in the generated code.

### PR DESCRIPTION
**Pull request by abhinav**
Each service gets its own submodule, and each function gets an Args struct, a
Result union, and an anonymous-struct-based variable that provides,

    func Args(arg1, arg2, ...) *MyFunctionArgs
    func IsException(error) bool
    func WrapResponse(returnType, error) (*MyFunctionResult, error)
    func UnwrapResponse(*MyFunctionResult) (returnType, error)

For example,

    // foo.thrift

    service Foo { string bar() }

    service Bar { void baz() }

Will generate,

    foo/        # package foo for foo.thrift
     |- foo/    # package foo for service Foo
         |- bar.go
             |- type BarArgs
             |- type BarResult
             |- Bar.Args() *BarArgs
             |- Bar.IsException(error) bool
             |- Bar.WrapResponse(string, error) (*BarResult, error)
             |- Bar.UnwrapResponse(*BarResult) (string, error)
     |- bar/    # package bar for service Bar
         |- baz.go
             |- type BazArgs
             |- type BazResult
             |- Baz.Args() *BazArgs
             |- Baz.IsException(error) bool
             |- Baz.WrapResponse(error) (*BazResult, error)
             |- Baz.UnwrapResponse(*BazResult) error

Note:

- The anonymous struct for void methods uses a single parameter rather than
  two.
- We're not generating a service interface. We're leaving that up to the
  library-specfic plugins.

Resolves #36, #61,

### CODE REVIEW

File: compile/service.go [hunk 1]
```diff
@@ -207,6 +207,11 @@ func (f *FunctionSpec) Link(scope Scope) error {
 	return nil
 }
 
+// HasReturn returns true if this function has a non-void return.
+func (f *FunctionSpec) HasReturn() bool {
+	return f.ResultSpec != nil && f.ResultSpec.ReturnType != nil
```
Comment (prashantv) [inline compile/service.go]: (unrelated to this PR), should we always have a `ResultSpec` for a function, even if it's void, and have the `ReturnType` be `nil`? I have a similar check in yab but it might be cleaner to assume `ResultSpec != nil`

File: gen/generator.go [hunk 2]
```diff
@@ -58,7 +58,7 @@ type Generator interface {
 	// module.
 	Import(path string) string
 
-	// Write the generated code to the given Writer.
+	// Write the generated code to the given Writer and end this file.
```
Comment (prashantv) [inline gen/generator.go]: what does `end this file` mean?

File: gen/service.go [hunk 3]
```diff
@@ -0,0 +1,225 @@
...
+//
+// Returns a map from file name to contents for that file. The file names are
+// relative to the package directory for the service.
+func Service(g Generator, s *compile.ServiceSpec) (map[string]*bytes.Buffer, error) {
+	files := make(map[string]*bytes.Buffer)
+
+	// TODO inherited service functions
+
+	for _, functionName := range sortStringKeys(s.Functions) {
+		err := ServiceFunction(g, s, s.Functions[functionName])
```
Comment (prashantv) [inline gen/service.go]: nit: can inline into `if`

File: gen/service.go [hunk 4]
```diff
@@ -0,0 +1,225 @@
...
+// ServiceFunction generates code for the given function of the given service.
+func ServiceFunction(g Generator, s *compile.ServiceSpec, f *compile.FunctionSpec) error {
+	if f.OneWay {
+		return fmt.Errorf(
+			"oneway functions are not yet supported: %s.%s is oneway",
+			s.Name, f.Name)
+	}
+
+	argsGen := fieldGroupGenerator{
+		Name:   goCase(f.Name) + "Args",
```
Comment (prashantv) [inline gen/service.go]: TODO clashes -- if a service has functions `Foo` and `FooArgs`, it would clash. Same for the result struct.

File: gen/service.go [hunk 5]
```diff
@@ -0,0 +1,225 @@
...
+		Fields: compile.FieldGroup(f.ArgsSpec),
+	}
+	if err := argsGen.Generate(g); err != nil {
+		return wrapGenerateError(fmt.Sprintf("%s.%s", s.Name, f.Name), err)
+	}
+
+	resultFields := make(compile.FieldGroup, 0)
+	if result := f.ResultSpec; result != nil {
```
Comment (prashantv) [inline gen/service.go]: another place where we skip skip a `nil` check for the `ResultSpec` if it was always set

File: gen/service.go [hunk 6]
```diff
@@ -0,0 +1,225 @@
...
+	return nil
+}
+
+func functionHelper(g Generator, f *compile.FunctionSpec) error {
+	return g.DeclareFromTemplate(
+		`
+		<$name := goCase .Name>
+
+		var <$name> = struct{
+			IsException func(error) bool
```
Comment (prashantv) [inline gen/service.go]: Let's add method docs to the struct fields here.

File: gen/service.go [hunk 7]
```diff
@@ -0,0 +1,225 @@
...
+	// throw a generic error.
+	return nil
+}
+
+func functionHelper(g Generator, f *compile.FunctionSpec) error {
+	return g.DeclareFromTemplate(
+		`
+		<$name := goCase .Name>
+
+		var <$name> = struct{
```
Comment (prashantv) [inline gen/service.go]: docs for this helper

File: gen/service.go [hunk 8]
```diff
@@ -0,0 +1,225 @@
...
+					if err == nil {
+						return &<$name>Result{}, nil
+					}
+			<end>
+					<if .ResultSpec>
+						<if .ResultSpec.Exceptions>
+							switch e := err.(type) {
+								<range .ResultSpec.Exceptions>
+								case <typeReferencePtr .Type>:
+									return &<$name>Result{<goCase .Name>: e}, nil
```
Comment (prashantv) [inline gen/service.go]: some people hit the `err != nil` but it's actually a `nil` error with a type,
https://github.com/uber/tchannel-go/issues/233

It might be worth checking in here
```
if e == nil {
  // do something
}
```
here's the fix in thrift-gen,
https://github.com/uber/tchannel-go/pull/240/files

File: gen/service.go [hunk 9]
```diff
@@ -0,0 +1,225 @@
...
+					if err == nil {
+						return &<$name>Result{Success: success}, nil
+					}
+			<else>
+				func(err error) (*<$name>Result, error) {
+					if err == nil {
+						return &<$name>Result{}, nil
+					}
+			<end>
+					<if .ResultSpec>
```
Comment (prashantv) [inline gen/service.go]: maybe add `HasExceptions` so you oly have one `<if>`.

File: gen/service.go [hunk 10]
```diff
@@ -0,0 +1,225 @@
...
+		`
+		<$name := goCase .Name>
+
+		var <$name> = struct{
+			IsException func(error) bool
+
+			Args func(
+				<range .ArgsSpec>
+					<if .Required>
+						<.Name> <typeReference .Type>,
```
Comment (prashantv) [inline gen/service.go]: if the `Name` clashes with a go keyword, this will fail to compile. the full list is at 
https://golang.org/ref/spec#Keywords

File: gen/service_test.go [hunk 11]
```diff
@@ -0,0 +1,402 @@
...
+		},
+		{
+			desc:           "deleteValue failure (2)",
+			unwrapResponse: keyvalue.DeleteValue.UnwrapResponse,
+			resultArg: &keyvalue.DeleteValueResult{
+				InternalError: &tv.InternalError{},
+			},
+			expectedError: &tv.InternalError{},
+		},
+	}
```
Comment (prashantv) [inline gen/service_test.go]: add tests for:
 - multiple errors are set
 - error and result are set
 - only result is set for void method

(these are all invalid, but i want to make sure we understand what happens in invalid cases)

File: gen/service_test.go [hunk 12]
```diff
@@ -0,0 +1,402 @@
...
+				InternalError: &tv.InternalError{},
+			},
+		},
+		{
+			desc: "deleteValue failure",
+			run: func() (interface{}, error) {
+				return keyvalue.DeleteValue.WrapResponse(errors.New("foo"))
+			},
+			expectedError: errors.New("foo"),
+		},
```
Comment (prashantv) [inline gen/service_test.go]: add a case where you provide a result and an error

**Comment by prashantv** [comment]
Completed review pass

File: compile/service.go (hunk 1 above)
Comment (abhinav) [inline compile/service.go]: Sure. I wanted to avoid changing that in this change as well. Created https://github.com/thriftrw/thriftrw-go/pull/98

File: gen/generator.go (hunk 2 above)
Comment (abhinav) [inline gen/generator.go]: Clarified in docs

File: gen/service.go (hunk 3 above)
Comment (abhinav) [inline gen/service.go]: :+1:

File: gen/service.go (hunk 4 above)
Comment (abhinav) [inline gen/service.go]: As discussed, appended `Helper` to the variable name. We can iterate on this if we decide this isn't good enough for the plugins.

File: gen/service.go (hunk 5 above)
Comment (abhinav) [inline gen/service.go]: True. Simplified now that #98 is merged.

File: gen/service.go (hunk 9 above)
Comment (abhinav) [inline gen/service.go]: No longer necessary because Resultspec is always non-nil

File: gen/service.go (hunk 6 above)
Comment (abhinav) [inline gen/service.go]: Punting docs as discussed. Created https://github.com/thriftrw/thriftrw-go/issues/100

File: gen/service.go (hunk 7 above)
Comment (abhinav) [inline gen/service.go]: https://github.com/thriftrw/thriftrw-go/issues/100

File: gen/service.go (hunk 8 above)
Comment (abhinav) [inline gen/service.go]: :+1:

File: gen/service.go (hunk 10 above)
Comment (abhinav) [inline gen/service.go]: True

File: gen/service_test.go (hunk 11 above)
Comment (abhinav) [inline gen/service_test.go]: :+1: 

Not sure what you mean by the third one, though. You can't have success set for a void method because that field doesn't exist.

File: gen/service_test.go (hunk 12 above)
Comment (abhinav) [inline gen/service_test.go]: :+1:

**Comment by abhinav** [comment]
Updated. Ready for second pass.

File: gen/generate.go [hunk 13]
```diff
@@ -188,7 +186,29 @@ func generateModule(m *compile.Module, i thriftPackageImporter, outDir string) e
...
+				return err
+			}
+			packageName := filepath.Base(importPath)
+
+			// TODO inherited service functions
+
+			g := NewGenerator(i, importPath, packageName)
+			serviceFiles, err := Service(g, service)
+			if err != nil {
+				return fmt.Errorf("could not code for %s: %v", serviceName, err)
```
Comment (prashantv) [inline gen/generate.go]: I think you accidentally a word in "could not code for". also mention service maybe, "could not generate code code service %s"

File: gen/generator.go [hunk 14]
```diff
@@ -37,15 +37,20 @@ import (
...
 	// context.
 	TextTemplate(s string, data interface{}, opts ...TemplateOption) (string, error)
 
-	// DeclareFromTemplate renders a template (in the text/template format)
-	// that generates Go code and includes all declarations from the template
-	// in the code generated by the generator.
+	// DeclareFromTemplate renders the given template, and includes the
+	// declarations from the generated Go code in the package being generated.
+	// The next call to Write will write these declarations and any other
+	// declerations that have not been written so far.
```
Comment (prashantv) [inline gen/generator.go]: typo "declerations"

File: gen/service.go [hunk 15]
```diff
@@ -0,0 +1,278 @@
...
+				s.Name, functionName, err)
+		}
+
+		buff := new(bytes.Buffer)
+		if err := g.Write(buff, token.NewFileSet()); err != nil {
+			return nil, fmt.Errorf("could not write %s.%s: %v", s.Name, functionName, err)
+		}
+
+		// TODO check for conflicts
+		files[strings.ToLower(functionName)+".go"] = buff
```
Comment (prashantv) [inline gen/service.go]: we should probably start with prefixing the service name, if we have 2 services with the same function name in the same thrift file, it'll clash straight away.

Comment (prashantv) [inline gen/service.go]: ignore me, since we're in separate packages, doesn't matter.

File: gen/generate.go (hunk 13 above)
Comment (abhinav) [inline gen/generate.go]: :+1: 

you accidentally the
the word code there

File: gen/generator.go (hunk 14 above)
Comment (abhinav) [inline gen/generator.go]: :+1:

File: gen/service_test.go [hunk 16]
```diff
@@ -0,0 +1,430 @@
...
+		{
+			desc: "deleteValue application error (2)",
+			run: func() (interface{}, error) {
+				return keyvalue.DeleteValueHelper.WrapResponse(&tv.InternalError{})
+			},
+			expectedResult: &keyvalue.DeleteValueResult{
+				InternalError: &tv.InternalError{},
+			},
+		},
+		{
```
Comment (prashantv) [inline gen/service_test.go]: test where you call `WrapResponse` with non-nil type but nil value

File: gen/service_test.go [hunk 17]
```diff
@@ -0,0 +1,430 @@
...
+		result, err := tt.run()
+		if tt.expectedError != nil {
+			assert.Equal(t, tt.expectedError, err, tt.desc)
+		} else {
+			assert.Equal(t, tt.expectedResult, result, tt.desc)
+		}
+	}
+}
+
+func TestWrapResponseNillError(t *testing.T) {
```
Comment (prashantv) [inline gen/service_test.go]: nit: typo, s/Nill/Nil. Maybe also make the name more specific, "TestWrapResponseTypedNilError" or something

**Comment by prashantv** [comment]
lgtm

**Comment by kriskowal** [comment]
Music to my eyes.

File: gen/service_test.go (hunk 17 above)
Comment (abhinav) [inline gen/service_test.go]: :+1:
